Portfolio
WagokiBry/Portfolio-setup-and-mobile-first pull request #4
Opened 2022-10-27 14:37 UTC by PeacefulWiser

Portfolio

2022-10-27 15:35 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @PeacefulWiser 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media0.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Meaningful commit messages ✔️ 
* Professional README file ✔️

## Required Changes:
- [ ] From now on kindly avoid creating new PRs for re-reviews, even if you get "required changes", please make the changes in the same branch and submit the same pull request to another review 👍
- [ ] As requested by the previous reviewer, kindly use the correct `font-family` as shown in Figma. You can import the font from google fonts (please check out this [link](https://fonts.google.com/specimen/Poppins?query=poppins)) or you can use a cdn.

_Kindly check the comments below_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 15:35 UTC, ha-manel commented on index.html
> +    <li><a href="#"><i class='fab fa-angellist'></i></a></li>
- [ ] As requested by the previous reviewer, kindly make these icons look more like the ones in Figma, this includes the color, the spacing between them and the alignment of the list 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/198334345-b3874737-7c5a-4e74-9015-e55374a914ee.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/198334395-3d8b3025-8af5-4dcc-a2cc-d1cc219f479d.png)

2022-10-28 06:13 UTC, jerryowusu approved these changes
Hi @PeacefulWiser 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![wow approved](https://user-images.githubusercontent.com/65233860/198516020-986d4da6-9697-48eb-adc1-2c68a33783c7.gif)

## Highlights
All linters are passing :heavy_check_mark: 
Followed Github flow :heavy_check_mark: 
Good commit messages :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 06:13 UTC, jerryowusu commented on index.html
> +            <a href="#">My Logo</a>
[OPTIONAL] Kindly put the logo outside the nav tag since it is not a navigation menu.

2022-10-28 06:13 UTC, jerryowusu commented on style.css
> +
There are some few disparities between your design and that of the figma. Kindly check and fix the white/blank space on the right side of your design. Also check the fonts and spacing to make sure it matches the design.

 Your design            |  The design template
:-------------------------:|:-------------------------:
![Screenshot from 2022-10-28 06-11-21](https://user-images.githubusercontent.com/65233860/198515825-f509482b-0cbc-4783-89fb-21e7287a208d.png)  |  ![Screenshot from 2022-10-28 05-25-32](https://user-images.githubusercontent.com/65233860/198510369-78d07027-522b-416d-acff-2d29123d8dc4.png)

2022-10-28 06:47 UTC, merged